development:
  adapter: postgresql
  host: db
  port: 5432
  database: inss_development
  username: postgres
  password: your_password

test:
  adapter: postgresql
  host: db
  port: 5432
  database: inss_test
  username: postgres
  password: your_password

production:
  adapter: postgresql
  host: db
  port: 5432
  database: inss_production
  username: postgres
  password: your_password
